### ISSUE TITLE
✨ feat: diseñar tests del proyecto

### ISSUE THREAD

**Issue by adrgarcha** [Mantecao-EGC/mantecao-hub#4]
Como se menciona en la práctica 4, diseñar los siguientes tests para el proyecto (no se especifica dónde ni cuántos tests):

- Diseña tests unitarios y de integración
- Diseña tests de carga con Locust (o similar)
- Diseña tests de vista con Selenium (o similar)

**Comment by Samalbalat** [comment]
Se estableció este trabajo en otras issues como #10 , #13 y #14
